ALTER SESSION SET CURRENT_SCHEMA = SIMAPP;

CREATE TABLE IOT_SIM (
  ICCID VARCHAR2(20) PRIMARY KEY,
  STATUS VARCHAR2(20),
  CUSTOMER_ID NUMBER,
  PLAN_CODE VARCHAR2(30),
  REGION VARCHAR2(10),
  CREATED_AT DATE
);

CREATE TABLE SIM_USAGE (
  ICCID VARCHAR2(20),
  USAGE_MB NUMBER,
  USAGE_DATE DATE
);

CREATE TABLE SIM_AUDIT_LOG (
  ID NUMBER PRIMARY KEY,
  ICCID VARCHAR2(20),
  ACTION VARCHAR2(50),
  COMMENTS VARCHAR2(400),
  CREATED_AT DATE
);
